# Generated by Django 5.1.3 on 2024-11-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_per_unit', models.IntegerField(help_text='Bir dona mahsulot uchun ketadigan vaqt (minutda)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker_time_per_day', models.IntegerField(default=500, help_text='Bir ishchining bir kundagi ishlash vaqti (minutda)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatokDailyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kutilayotgan', models.FloatField(editable=False, help_text='Kutilayotgan mahsulot soni')),
                ('real_ish', models.IntegerField(default=0, help_text='Haqiqiy ishlab chiqarilgan mahsulot soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.product')),
            ],
        ),
        migrations.CreateModel(
            name='PatokDailyIsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers_count', models.IntegerField(help_text='Ishchilar soni')),
                ('total_minutes', models.IntegerField(editable=False, help_text='Umumiy ishchi vaqti (workers_count * worker_time_per_day)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productlar', models.ManyToManyField(related_name='daily_production_product', to='patok.patokdailyproducts')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.productionline')),
            ],
        ),
        migrations.CreateModel(
            name='SoatlikProductPatok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text="Bir soatda ishlab chiqariladigan mahsulot soni'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.productionline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.product')),
            ],
        ),
    ]
