# Generated by Django 5.1.3 on 2024-11-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workers_count', models.IntegerField(help_text='Ishchilar soni')),
                ('total_minutes', models.IntegerField(editable=False, help_text='Umumiy ishchi vaqti (workers_count * worker_time_per_day)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_per_unit', models.IntegerField(help_text='Bir dona mahsulot uchun ketadigan vaqt (minutda)')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('worker_time_per_day', models.IntegerField(default=500, help_text='Bir ishchining bir kundagi ishlash vaqti (minutda)')),
            ],
        ),
        migrations.CreateModel(
            name='DailyProductionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.FloatField(editable=False, help_text='Kutilayotgan mahsulot soni')),
                ('actual_quantity', models.IntegerField(default=0, help_text='Haqiqiy ishlab chiqarilgan mahsulot soni')),
                ('daily_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.dailyproduction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.product')),
            ],
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='products',
            field=models.ManyToManyField(through='patok.DailyProductionProduct', to='patok.product'),
        ),
        migrations.CreateModel(
            name='ProductionHourlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(help_text='Shu vaqtgacha qilingan mahsulot soni')),
                ('minutes_spent', models.IntegerField(help_text='Ushbu mahsulot uchun sarflangan vaqt (minutda)')),
                ('daily_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.dailyproduction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.product')),
            ],
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='production_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patok.productionline'),
        ),
    ]
