# Generated by Django 5.1.3 on 2024-11-25 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='soatlikproductpatok',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soatlikproductpatok',
            name='patokdailyish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patok.patokdailyish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soatlikproductpatok',
            name='patokproducts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patok.patokdailyproducts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patokdailyproducts',
            name='kutilayotgan',
            field=models.FloatField(default=0, editable=False, help_text='Kutilayotgan mahsulot soni'),
        ),
        migrations.AlterField(
            model_name='soatlikproductpatok',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soatlikproductpatok',
            name='clock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patok.clock'),
            preserve_default=False,
        ),
    ]
